### ISSUE TITLE
issue: Missing/Corrupted Images

### ISSUE THREAD

**Issue by Aviortheking** [tcgdex/cards-database#105]
_found another missing images? create a new issue or comment below_

- [ ] DE,ES,IT,PT < SWSH

# All languages

### SWSH

- [x] Fusion Strike
- [x] Evolving skies
- [ ] Pokémon Futsal Collection

### E-Card

- [ ] Best of game
- [ ] Sample

### EX

- [ ] Poké Card Creator Pack

### Base

- [ ] W Promotional (Base)

### Macdonald's collections

- [ ] Macdonald's Collection 2011
- [ ] Macdonald's Collection 2012
- [ ] Macdonald's Collection 2013
- [ ] Macdonald's Collection 2014 English
- [ ] Macdonald's Collection 2014 French
- [ ] Macdonald's Collection 2015
- [ ] Macdonald's Collection 2016
- [ ] Macdonald's Collection 2017
- [ ] Macdonald's Collection 2018
- [ ] Macdonald's Collection 2019

## Trainer Kits

- [ ] DP trainer Kit (Lucario)
- [ ] DP trainer Kit (Manaphy)
- [ ] EX trainer Kit (Latias).ts
- [ ] EX trainer Kit (Latios).ts
- [ ] EX trainer Kit 2 (Ninun).ts
- [ ] EX trainer Kit 2 (Plusle).ts
- [ ] HS trainer Kit (Excadrill).ts
- [ ] HS trainer Kit (Gyarados).ts
- [ ] HS trainer Kit (Raichu).ts
- [ ] HS trainer Kit (Zoroark).ts
- [ ] SM trainer Kit (Alolan Raichu).ts
- [ ] SM trainer Kit (Lycanroc).ts
- [ ] XY trainer Kit (Bisharp).ts
- [ ] XY trainer Kit (Latias).ts
- [ ] XY trainer Kit (Latios).ts
- [ ] XY trainer Kit (Noivern).ts
- [ ] XY trainer Kit (Pikachu Libre).ts
- [ ] XY trainer Kit (Suicune).ts
- [ ] XY trainer Kit (Sylveon).ts
- [ ] XY trainer Kit (Wigglytuff).ts

**Comment by Aviortheking** [comment]
@all-contributors add @JuneTwooo bug

**Comment by Maxopoly** [comment]
[base1-1](https://assets.tcgdex.net/en/base/base1/1/high.png) is corrupted at high resolution

**Comment by Aviortheking** [comment]
Fixed, thanks for the report !

**Comment by Aviortheking** [comment]
Also fixed !

**Comment by Aviortheking** [comment]
Closing in favor of the status page (https://api.tcgdex.net/status) if you have any cards that have errors, pleasecreate a new issue ! :D
