### ISSUE TITLE
[Up]: No cards in "Base Set" for fr translation

### ISSUE THREAD

**Issue by Kevin-Adrea** [tcgdex/cards-database#126]
### Data affected

- [ ] Card
- [X] Set
- [ ] Serie
- [ ] Other
- [ ] new Data Type

### Please explain in more details what idea you have

There is no cards in `fetchSet('Set de Base')` for fr translation (works for en)

FR :
![image](https://user-images.githubusercontent.com/36231620/139829733-f87edd98-5fa1-4793-89fa-9bd6fe70efbf.png)

EN :
![image](https://user-images.githubusercontent.com/36231620/139829908-11e25b51-ddb9-4187-b9c3-63d94623ae09.png)

Is this normal ?
Thank you !

**Comment by Aviortheking** [comment]
Currently I have no source to give me data for pre HGSS cards for languages other than English.

I am building (in early early early state) an OCR to automaticly translate cards but it takes a lot of time or would need some other people to help me manually input each cards but both of theses options take a lot of time

This is pretty high in my todo list

Also if you need pictures for the FR sets they should be available (just replace the `en` by `fr`)

**Comment by Kevin-Adrea** [comment]
Thanks for the last tips, exactly what I needed !

**Comment by Aviortheking** [comment]
@all-contributors add @Kevin-Adrea bug

**Comment by Aviortheking** [comment]
Great news ! with the commit ffdd3b4656dc76102320c4a18e18140455de41ff French cards for the base serie should all be there !
so i'm closing it
