### ISSUE TITLE
issue: Corrupted french images

### ISSUE THREAD

**Issue by JuneTwooo** [tcgdex/cards-database#262]
### What seems to be the issue

Card

### Field(s)

Images

### Description

Theses cards images are corrupted in french :

- [x] xyp-XY15
- [x] xyp-XY19
- [x] xyp-XY25
- [x] xyp-XY29
- [x] xyp-XY30
- [x] xyp-XY34
- [x] xyp-XY40
- [x] xyp-XY42
- [x] xyp-XY43
- [x] xyp-XY44
- [x] xyp-XY52
- [x] xyp-XY53
- [x] xyp-XY61
- [x] xyp-XY62
- [x] xyp-XY80
- [x] xyp-XY133
- [x] xyp-XY139
- [x] xyp-XY140
- [x] xyp-XY155
- [ ] xyp-XY156

Exemple : [https://www.tcgdex.net/_next/image?url=https%3A%2F%2Fassets.tcgdex.net%2Ffr%2Fxy%2Fxyp%2FXY15%2Fhigh.webp&w=3840&q=100](url)

**Comment by Aviortheking** [comment]
Thanks for the report !
It should now be fixed (the www.tcgdex.net assets have additionnal cache, but the API one should have already changed!)
