### ISSUE TITLE
issue: Fetching Set swsh8 ignores lower cardnumbers

### ISSUE THREAD

**Issue by Thorn2910** [tcgdex/cards-database#466]
### What seems to be the issue

Set

### Field(s)

id or localID

### Description

With Javascript SDK 
`tcgdex.fetch('sets', 'swsh8', 53)`

will result in swsh8-153 Pokemon

Same with `tcgdex.fetch('sets', 'swsh8', 2)`

will result in swsh8-102 Pokemon

swsh3 seems to have the same issue

Different sets (sv02 / swsh12.5 / swsh12 / swsh9) don't seem to have this issue

Worked yesterday (02.01.24)

**Comment by Thorn2910** [comment]
Seems that sets with issues have this naming in data
![grafik](https://github.com/tcgdex/cards-database/assets/13822818/fde19e76-e8bc-4500-9788-1d23af6db77d)

whereas stes without this issue have this naming
![grafik](https://github.com/tcgdex/cards-database/assets/13822818/109225e0-7258-40f8-90e2-ff3377797ada)

**Comment by Aviortheking** [comment]
Hi, thanks for the issue, I have identified the issue and will resolve it quickly !

**Comment by Aviortheking** [comment]
Actually, it was solved with the latest commit that solve the invalid sorting strategy ! 8fd7afe

It was uploaded to Production and won't happen again !

Thanks for your patience
