### ISSUE TITLE
issue: fetch sets not using the correct set ID

### ISSUE THREAD

**Issue by Thorn2910** [tcgdex/cards-database#471]
### What seems to be the issue

Set

### Field(s)

set ID

### Description

When using 

```javascript

tcgdex.fetch('sets', 'swsh12', 10)

``` 

returns Set **swsh12.5** card 10

seems to happen with some sets which also has the .5 extenstion (tested swsh12 / swsh4 /swsh3 --> they return the .5 set)
set "sm7" retruns the correct "sm7" set

also swsh1 retruns set swsh10

**Comment by Aviortheking** [comment]
thanks for the wait, the bug was found and is being uploaded to the server as we speak
