### ISSUE TITLE
enhancement: Add a `firstSet`/`lastSet` fields

### ISSUE THREAD

**Issue by Aviortheking** [tcgdex/cards-database#536]
### Data affected

- [ ] Card
- [ ] Set
- [x] Serie
- [ ] Other
- [ ] new Data Type

### Please explain in more details what idea you have

add the ability to get the first and last released sets of a serie

**Comment by dleiva04** [comment]
Can I get this assigned to me? @Aviortheking 

Also, since this is like a flag for the endpoint, should we do something like

v2/:lang/sets/first and v2/:lang/sets/last?

**Comment by Aviortheking** [comment]
As a first step it would be awesome to have it in the `series/:serie` URL, two fields `firstSet` and `lastSet`

**Comment by dleiva04** [comment]
Awesome! Let me do it
