### ISSUE TITLE
enhancement: Add or modify cards endpoint to include more details

### ISSUE THREAD

**Issue by dsnidr** [tcgdex/cards-database#594]
### Data affected

- [X] Card
- [ ] Set
- [ ] Serie
- [X] Other
- [ ] new Data Type

### Please explain in more details what idea you have

**My Use-case**

I have an app which periodically fetches data for all cards and builds a local mirror to avoid spamming API requests.

Currently, the only way to fetch the details I need using this API is to fetch cards one by one. There is the `GET /v2/en/cards` endpoint which will return partial data on all cards, but does not include fields I need such as:

- set details
- rarity
- images
- variants
- etc...

**Proposed Solution**

I propose a paginated endpoint which will return full card objects, but only up to a sane limit (e.g 50 at a time). Ideally, it would also support basic sorting and other standard operations.

Having a paginated endpoint returning full card details would have the following benefits:

1. Make the API easier and faster to work with
2. Reduce load on the API by avoiding the overhead associated with tens of thousands of individual requests to fetch all cards
3. It could provide a count of the total number of cards in the database

I'm happy to give this more thought and take up the implementation if this idea is well received.

**Comment by dsnidr** [comment]
Great! I'll just use that, then.

Do you think it's worth exploring a REST option for those who don't want to use GraphQL? If not, feel free to close this. 

Thanks! :smile:

**Comment by Aviortheking** [comment]
There is something that is meant to kinda add this in #606 (Strangely it was on the Discord but I forgot to add it to the Github)
