### ISSUE TITLE
issue: No image available for FR translation in Cosmic Eclipse set

### ISSUE THREAD

**Issue by FXCHASSAGNE** [tcgdex/cards-database#605]
### What seems to be the issue

Card

### Field(s)

image

### Description

No image available for Vaporeon (42) from set Cosmic Eclipse (sm12) for translation fr (en is ok).
https://api.tcgdex.net/v2/en/sets/sm12/42 =>"image": "https://assets.tcgdex.net/en/sm/sm12/42",
https://api.tcgdex.net/v2/fr/sets/sm12/42 => image field is missing

I run a little script to check every pokemon of this set and I found that images are missing for pokemon :  
_**- frenchName (id)**_
- Ortide (3)
- Rafflesia GX (4)
- Saquedeneu (5)
- Bouldeneu (6)
- Tournegrin (7)
- Héliatronc (8)
- Scarhino (9)
- Entei (28)
- Chartor (29)
- Victini (30)
- Gruikui (31)
- Grotichon (32)
- Roitiflam (33)
- Pyronille (34)
- Pyrax GX (35)
- Hélionceau (36)
- Némélios (37)
- Tortank et Tiplouf GX (38)
- Goupix d’Alola (39)
- Psykokwak (40)
- Akwakwak (41)
- Aquali (42)
- Farfuret (43)
- Dimoret (44)
- Wailmer (45)
- Wailord (46)
- Stalgamin (47)
- Oniglali (48)
- Obalie (49)
- Obalie (50)
- Phogleur (51)
- Kaimorse (52)
- Kyogre (53)
- Tiplouf (54)
- Prinplouf (55)
- Pingoléon (56)
- Phione (57)
- Tritonde (58)
- Couaneton (59)
- Lakmécygne (60)
- Kyurem Noir (61)
- Froussardine (62)
- Froussardine GX (63)
- Araqua (64)
- Tarenbulle (65)
- Pikachu (66)
- Raichu (67)
- Magnéti (68)
- Magnéton (69)
- Voltali (70)
- Loupio (71)
- Lanturn (72)
- Togedemaru (73)
- Togedemaru (74)
- Solgaleo et Lunala GX (75)
- Smogo (76)
- Smogogo (77)
- Natu (78)
- Xatu (79)
- Tarsal (80)
- Kirlia (81)
- Gallame (82)
- Skelénox (83)
- Téraclope (84)
- Noctunoir (85)
- Motisma (86)
- Chovsourir (87)
- Rhinolove (88)
- Gringolem (89)
- Golemastoc (90)
- Venalgue (91)
- Kravarech (92)
- Brocélôme (93)
- Desséliande (94)
- Plumeline GX (95)
- Mimiqui (96)
- Mimiqui (97)
- Sinistrail (98)
- Cosmog (99)
- Appel aux Escouades (270)
- Énergie de Pioche (271)

Thanks in advance

**Comment by Aviortheking** [comment]
Thanks, I'll add them right now !

**Comment by Aviortheking** [comment]
They are now in the assets !
It will be available through the API on the next build !
